site_name: Documentation Demo
site_url: https://arubion.github.io/
site_description: Demo

repo_url: https://github.com/IlustreEarl/my-demo
edit_uri: ../master/docs

theme: 
    name: 'material'
    language: 'en'

extra_css:
  - 'stylesheets/extra.css'

plugins:
  - search:
      lang: ['en']

nav: 
- Home: en/index.md
- About: en/about.md
- License: en/license.md
- General Recommendations: 
    - ID Photos: en/idphotorec.md
    - User Photos: en/userphotorec.md
    - Transfer Parameters: en/transferparams.md
    - Integration: en/integrationrec.md
    - General Errors: en/generalerrors.md
- Face Matching Integration:
    - Face Matching - Description: en/facematchingep.md
    - Operation - Face Matching: en/facematching.md

copyright: '© 2019, Cyxtera Cybersecurity, Inc. All rights reserved.'
